export const GET_FACELOG_IN_GROUP_REQUEST = 'GET_FACELOG_IN_GROUP_REQUEST';
export const GET_PERSON_FACELOG_REQUEST = 'GET_PERSON_FACELOG_REQUEST';
export const GET_KNOWN_FACELOG_REQUEST = 'GET_KNOWN_FACELOG_REQUEST';
export const GET_UNKNOWN_FACELOG_REQUEST = 'GET_UNKNOWN_FACELOG_REQUEST';
export const GET_UNDETECTED_FACELOG_REQUEST = ' GET_UNDETECTED_FACELOG_REQUEST';
export const GET_FACELOG_SUCCESS = 'GET_FACELOG_SUCCESS';
export const GET_FACELOG_FAILED = 'GET_FACELOG_FAILED';