export const GET_ALL_PERSONGROUP_REQUEST = 'GET_ALL_PERSONGROUP_REQUEST';
export const GET_ALL_PERSONGROUP_SUCCESS = 'GET_ALL_PERSONGROUP_SUCCESS';
export const GET_ALL_PERSONGROUP_FAILED = 'GET_ALL_PERSONGROUP_FAILED';

export const ADD_PERSONGROUP_REQUEST = 'ADD_PERSONGROUP_REQUEST';
export const ADD_PERSONGROUP_SUCCESS = 'ADD_PERSONGROUP_SUCCESS';
export const ADD_PERSONGROUP_FAILED = 'ADD_PERSONGROUP_FAILED';

export const ADD_PERSON_REQUEST = 'ADD_PERSON_REQUEST';
export const ADD_PERSON_SUCCESS = 'ADD_PERSON_SUCCESS';
export const ADD_PERSON_FAILED = 'ADD_PERSON_FAILED';

export const DELETE_PERSONGROUP_REQUEST = 'DELETE_PERSONGROUP_REQUEST';
export const DELETE_PERSONGROUP_SUCCESS = 'DELETE_PERSONGROUP_SUCCESS';
export const DELETE_PERSONGROUP_FAILED = 'DELETE_PERSONGROUP_FAILED';

export const DELETE_PERSON_REQUEST = 'DELETE_PERSON_REQUEST';
export const DELETE_PERSON_SUCCESS = 'DELETE_PERSON_SUCCESS';
export const DELETE_PERSON_FAILED = 'DELETE_PERSON_FAILED';

export const UPDATE_TRAINING_STATUS = 'UPDATE_TRAINING_STATUS';

export const CHANGE_DEFAULT_GROUP_REQUEST = 'CHANGE_DEFAULT_GROUP_REQUEST';
export const CHANGE_DEFAULT_GROUP_SUCCESS = 'CHANGE_DEFAULT_GROUP_SUCCESS';
export const CHANGE_DEFAULT_GROUP_FAILED = 'CHANGE_DEFAULT_GROUP_FAILED';