export const GET_PERSONFACE_REQUEST = 'GET_PERSONFACE_REQUEST';
export const GET_PERSONFACE_SUCCESS = 'GET_PERSONFACE_SUCCESS';
export const GET_PERSONFACE_FAILED = 'GET_PERSONFACE_FAILED';

export const ADD_FACE_REQUEST = 'ADD_FACE_REQUEST';
export const ADD_FACE_SUCCESS = 'ADD_FACE_SUCCESS';
export const ADD_FACE_FAILED = 'ADD_FACE_FAILED';

export const DELETE_FACE_REQUEST = 'DELETE_FACE_REQUEST';
export const DELETE_FACE_SUCCESS = 'DELETE_FACE_SUCCESS';
export const DELETE_FACE_FAILED = 'DELETE_FACE_FAILED';